name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install apt packages
      run: xargs sudo apt-get install apt_requirements.txt
      
    - name: Install Python3 dependencies
      run: pip3 install -r pip_requirements.txt
      
    - name: Run all simulations
      run: ./run_all_tests.sh
